# Generated by Django 4.1.5 on 2023-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Herramientas',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='LaborIndirecta',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Material',
        ),
        migrations.AddField(
            model_name='factura',
            name='Herramientas',
            field=models.ManyToManyField(to='presupuesto2.herramientas'),
        ),
        migrations.AddField(
            model_name='factura',
            name='LaborIndirecta',
            field=models.ManyToManyField(to='presupuesto2.laborindirecta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='Material',
            field=models.ManyToManyField(to='presupuesto2.material'),
        ),
    ]
