# Generated by Django 4.1.5 on 2023-02-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto2', '0002_remove_factura_herramientas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
