# Generated by Django 4.1.5 on 2023-02-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto2', '0003_alter_material_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=2),
        ),
    ]
